### ISSUE TITLE
[Bug] enabled command wrong in door interaction

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#100]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> When enabling/ disabling the door interaction flag you type ``enable true/false`` however this should be ``enabled/disabled ``

## How to reproduce?

>> run the command

**Comment by Lukamon24** [comment]
done
