### ISSUE TITLE
[Bug] Block break flag view states group is "Optional.empty"

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#103]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> When viewing the flag info of the block break, if the group is empty, the return value states "Optional.empty", this should be "None"

## How to reproduce?

>> Run the view command for block break

**Comment by Lukamon24** [comment]
done ig
