### ISSUE TITLE
[Bug] Version info wrong

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#105]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> When viewing the info of the plugin, the version info displays as ``${version}`` but should be 1.0.0.0. 

## How to reproduce?

>> Run the command ``/zone zone plugin info``

**Comment by Lukamon24** [comment]
done
