### ISSUE TITLE
[Bug] Version info has wrong command

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#106]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> Version info currently has the command ``/zone zone plugin info`` this should be ``/zone plugin info`` 

## How to reproduce?

>> Run the command

**Comment by Lukamon24** [comment]
well did this when i watched the stream, not needed to create an issue

**Comment by mosemister** [comment]
Create a issue for everything, makes it easy to keep track of what has been fixed
