### ISSUE TITLE
[Bug] 0 and 1 get suggested when changing players group

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#107]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> A suggestion of 0 or 1 gets suggested after the change group command is written. This seems to be in a remaining argument type

## How to reproduce?

>> type the change group command

**Comment by mosemister** [comment]
Stop assigning me to stuff. Assignment means I want to work on it asap.

**Comment by Lukamon24** [comment]
> Stop assigning me to stuff. Assignment means I want to work on it asap.

oopsie sowwy
