### ISSUE TITLE
[Bug] Not all group keys are added by default

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#109]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> Not all group keys are added by default

## How to reproduce?

>> Launch zones

## Extra info

>> While this may seem like a big issue, its not as there is (or at least should be) a group command for each key required to change

**Comment by Lukamon24** [comment]
done
