### ISSUE TITLE
[Bug] No group key change command for commands

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#110]
# Bug Report

## Version info

Zone Version: x.x.x.x
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> Some commands do not have the ability to change the group key's group

## How to reproduce?

>> Launch the plugin

## Extra info

- [ ] Player attack prevention
- [ ] Player fall damage
- [ ] Player damage

**Comment by Lukamon24** [comment]
meh

**Comment by Lukamon24** [comment]
RIP me

**Comment by mosemister** [comment]
Why was i assigned to this?
