### ISSUE TITLE
[Bug] Entering prevented zone will give greetings message

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#120]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> When entering a zone you are not allowed to via the prevention flag, the prevention flag will kick in and kick the player out (expected). However the player gets the greeting message on every attempt

## How to reproduce?

>> Enable greetings message and the prevention flag. Ensure you do not have permission to enter zone. Attempt to enter zone

## Extra info

By lowering the priority of the greetings message and ensuring that the greeting message does not run when the event is cancelled, then the result should be expected

**Comment by Lukamon24** [comment]
done
