### ISSUE TITLE
[Bug] No set group for attack damage

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#121]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> The command ``/zone region <zoneid> flag damage attack set group <groupid>`` is missing

## How to reproduce?

>> Launch the plugin

**Comment by Lukamon24** [comment]
ey done ig bruh
