### ISSUE TITLE
[Bug] No view command for damage attack 

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#124]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> No command of ``zone region <zoneid> flag damage attack view``

## How to reproduce?

>> Launch the plugin

**Comment by Lukamon24** [comment]
done
