### ISSUE TITLE
[Bug] Wool can be broken in bounds shown

### ISSUE THREAD

**Issue by Lukamon24** [Zone-Protect/Zone-protect#127]
# Bug Report

## Version info

Zone Version: 1.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug
- The wool can be broken that is showing the bounds. The command is: `/zone region info zones:luke bounds show`

## How to reproduce?
- Change it so that you can break the block but it will reset
>> How to cause the bug
- Run the command `/zone region info zones:luke bounds show`
## Extra info
- If possible, change the show argument into a boolean argument like the second one would be `/zone region info zones:luke 
bounds hide`
### Crash report?

```txt
Paste crash report here if possible
```

**Comment by mosemister** [comment]
Are you saying that before the show command, you couldnt break wool, but after you could?

**Comment by Lukamon24** [comment]
emm nah the bound is shown using wool, I am saying that the wool that are showing the bounds can be broken

**Comment by mosemister** [comment]
Oh. They are fake blocks so dont really care about that. They dont ... Or shouldn't drop anything

**Comment by Lukamon24** [comment]
emm ok.. but can u make it this way like just u know making it kind of un-existing i.e. a player can go through the block or make it unbreakable not even the animation will display

**Comment by mosemister** [comment]
Not that im aware of. The way fake blocks works is it sends the block data to only one person. As far as the server and anyone else is aware, that block doesnt exist. 

Not being able to go though it and the animation of it being broken is all client side (something we cant touch). 

Maybe able to listen to the interaction event and see if the fake block is being interacted with, if so reset that position

**Comment by Lukamon24** [comment]
yeah or if broken reset the block that's the best

**Comment by Lukamon24** [comment]
what say?

**Comment by mosemister** [comment]
Not sure if it can be detected. As in the hit block in interact may be server side, which means it would be the block the player was supposed to hit. 

Another option would be setting it as a block such as water

**Comment by Lukamon24** [comment]
ok useless
