### ISSUE TITLE
[Bug] Fall damage view command inconsistant

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#134]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> In the current version of zones, all fall damage flag commands are ``zone region flag <zone> damage fall`` however the view command is ``zone region flag <zone> fall damage

## How to reproduce?

>> Attempt to run the command

**Comment by Lukamon24** [comment]
will do ASAP
