### ISSUE TITLE
[Feature] Default zone join groups

### ISSUE THREAD

**Issue by Lukamon24** [Zone-Protect/Zone-protect#162]
# Feature request: Code

## Description of code
When a player joins a zone/sub-zone, the player should get a membership group

GroupKey: ``default_group``

## What would this break

- Nothing

**Comment by mosemister** [comment]
What if the zone doesnt have those groups? the only group that is guarenteed is the "zones:visitor" group. 

There should be a specific ``GroupKey`` which is added to the specified group. 

BTW, there arnt any groups that are seperate depending on regular zone and sub zones
