### ISSUE TITLE
[Feature] Reload

### ISSUE THREAD

**Issue by Lukamon24** [Zone-Protect/Zone-protect#179]
### Zone-Version

1.0.0

### Sponge API version

- [X] 8.0.0
- [ ] 8.1.0
- [ ] 9.0.0

### Sponge type

- [X] Vanilla
- [ ] Forge
- [ ] Lantern

### Description of bug - How you caused it

Sponge reload command doesn't work for Zone-Protect because Zone-Protect doesn't know how to reload since Zone-Protect doesn't have a java class which listens to the reload event. So add one.

**Comment by mosemister** [comment]
This was never a issue in the first place, so its a feature request ;)

**Comment by Lukamon24** [comment]
Ok XD
