### ISSUE TITLE
[Bug] SonarCloud detected bugs

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#214]
### Zone-Version

1.0.1

### Sponge API version

- [X] 8.0.0
- [X] 8.1.0
- [X] 9.0.0

### Sponge type

- [X] Vanilla
- [X] Forge
- [X] Lantern

### Description of bug - How you caused it

https://sonarcloud.io/project/issues?id=Zone-Protect_Zone-protect&branch=master&resolved=false&types=BUG

**Comment by Lukamon24** [comment]
Yeah on it

**Comment by Lukamon24** [comment]
Why did u tick Lantern though

**Comment by mosemister** [comment]
Would have affected Lantern too ;)
