### ISSUE TITLE
[Flag] add greetings flag

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#3]
Greetings flag requires a Component FlagValue 

- when a user enters a zone with the greetings flag enabled, then send the attached message
- add the command ``zone flags <zone> greetings message set [message]``
- add the command ``zone flags <zone> greetings view``
- add the command ``zone flags <zone> greetings remove message``
- permission to create own ``zone.region.flag.greetings.own.create``
- permission to remove own ``zone.region.flag.greetings.own.remove``
- permission to create others
- permission to remove others
By not specifying a message, it wont send a message to the user (not removing the flag)

**Comment by Lukamon24** [comment]
PROGRESS

**Comment by Lukamon24** [comment]
PR..

**Comment by Lukamon24** [comment]
DUNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

**Comment by Lukamon24** [comment]
hey spelling error "add the commans zone flags <zone> greetings remove message"

**Comment by Lukamon24** [comment]
well well did u add permissions?
