### ISSUE TITLE
[Flag] Prevent players

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#5]
Add a Group permission flag for preventing players from entering a zone. 

This one is a easy one. 

- Add a groupKey (there is a GroupKeys class, just add it in there, no need for another class)
- Add a group based flag that is also a enabled flag (implements both ``Flag.Grouped`` and ``Flag.Enabled``
- Add listener for when a player enters a new zone (can copy and paste from greetings)
- cancel the event if a player is now entering a zone
- Add a command to enable/disable the player prevention ``zone region flag access player <true/false>``
- Ensure the listener for the player move event has a higher priority then the greetings (I would put the priority of greetings to LOWEST)

For consistancy, I would also change the Monster prevention flag to match the command pattern as this one

**Comment by Lukamon24** [comment]
whooops
