### ISSUE TITLE
[Feature] [Flag] Request to join

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#69]
# Feature request: Misc

## Description of feature?

Ability for a user to request to join a group. 
This will notify those who have a paticular GroupFlag when they join that a user wished to join the ranks.

Zones can be set to private (or semi private) where users will not be able to request to join (semi private will exclude only some players from being able to join). 

## Implementation

I am suggesting two flags. 

### Visibility flag

This will change if a player can request to join this group. The status's will be either ``private``, ``semi-private`` and ``public``.
with the other properties of the flag including ``excluded-players``
> Whereby players in this list cannot request to join
and ``include-sub-regions``
> Whereby sub regions cannot be bought nor rented to those who arnt public facing, however if disabled, then despite the zone being private, they can still join by renting/buying a sub region

**Comment by mosemister** [comment]
Moved to version 1.0.0 due to how quick all tasks were complete

**Comment by Lukamon24** [comment]
damn long log XD
