### ISSUE TITLE
[Bug] Incorrect changed group message

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#98]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> When a user changes group, they get the message of ``Moved Optional[<username>] from X to Y``

## How to reproduce?

>> Run the command to change a players group

**Comment by Lukamon24** [comment]
done
